language: node_js
node_js:
  - "11.10.1"
install:
  - yarn add global codecov
jobs:
script:
  - yarn test
  - codecov
include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
        - npx semantic-release