language: node_js
node_js:
  - "11.10.1"
jobs:
  include:
    - stage: test
      script:
      - yarn add global codecov
      - yarn test
      - codecov
    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn build
          - npx semantic-release
