language: node_js
node_js:
  - "11.10.1"
install:
  - yarn add global codecov
jobs:
  include:
    - stage: test
      script:
      - yarn test
      - codecov
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release